### ISSUE TITLE
Fails on `book-store` on the website

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/lua-test-runner#76]
I haven't been able to work out exactly what's wrong. I can get my solution and the example solution to pass locally using `./bin/run.sh` and `./bin/run-in-docker.sh`, but I can't get even a trivial solution to run on the website. 

I can get a useful error by running:

```lua
return { total =  3 }
```

which yields:

```
We received the following error when we ran your code:

./book-store_spec.lua:6: attempt to call a number value (field 'total')
```

but if I extend this just a bit to:

```lua
return { total = function() end }
```

then I get:

```
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```

I don't understand why I see different results running in the docker container. Is there a way to see the raw output of a given run on the website?

**Comment by imolein** [comment]
I guess I can reproduce the error with `run-in-docker.sh` on my system. It produces an empty `result.json` and I currently look into it why this is happening.

**Comment by imolein** [comment]
![93qycn](https://github.com/user-attachments/assets/0d5a92ca-dcaa-441b-a30a-93ab05b7fb3e)

I have to make the parsing of the spec file more stable I guess...
